version: '3.6'

services:
  rent-tracker:
    container_name: rent-tracker
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem